/**
 * Marktforschung Fensterreinigung NRW/Aachen – Stand Juli 2026
 *
 * Jede Formular-Option wurde gegen mindestens 20 unabhängige Quellen
 * (lokale Anbieter, Preisrechner, Branchenportale, Preislisten) geprüft.
 * Quellen-IDs verweisen auf FIRM_SOURCES unten.
 *
 * Verwendung: lib/pricing.ts – keine Schätzwerte ohne Referenz.
 */

export const FIRM_SOURCES = {
  kirchberger: "Kirchberger Fensterreinigung Aachen",
  mrCleaner: "Mr. Cleaner Aachen",
  inmaculado: "Inmaculado Aachen",
  besteReinigung: "BesteReinigung Baesweiler/Aachen",
  hajo: "Hajo Fensterreinigung Aachen",
  multiClean: "MultiClean Aachen",
  aixClean: "AIX Clean Aachen",
  gebaeudeMeister: "GebäudeMeister Aachen",
  gmPreisrechner: "GM Preisrechner (NRW)",
  cleanCalc: "CleanCalc (Branchen-SaaS)",
  reinigungSimon: "Reinigung Simon (Preisguide 2026)",
  auftragsGlueck: "AuftragsGlück",
  damato: "D'Amato Dienstleistungen",
  ihrefensterputzer: "ihrefensterputzer.de",
  freundlicheHausmeister: "Freundliche Hausmeister",
  nbFenster: "NB-Fensterreinigung",
  komplettSorglos: "KomplettSorglos",
  extraSauber: "ExtraSauber",
  deinefensterputzer: "Deine Fensterputzer Berlin",
  kleibrink: "Kleibrink NRW",
  myHammer: "MyHammer Aachen",
  mmCompact: "MMCompact Reinigung",
  scheibelKlar: "Scheibel Klar Preisliste",
  fensterversand: "Fensterversand.com Preisguide",
  portal11880: "11880 Gebäudereinigung Preisvergleich",
  gegenwashilft: "GegenwasHilft.de",
  cleanWhale: "CleanWhale",
  meisterJob: "Meister-Job Glasdach",
  fimi: "FIMI Gebäudereinigung Bayern",
  fixFenster: "Fix Fensterreinigung",
  nickReinigung: "Nick Reinigung",
  weserbergland: "Weserbergland Dienstleistungen Hameln",
  meliteo: "Meliteo Facility",
  bolch: "Bolch Insektenschutz",
  apriori: "Apriori Cleaning Rhein-Main",
  seimsolar: "Seimsolar PV",
  energieExperten: "Energie-Experten.org PV",
  heimcheck: "Heimcheck Solar",
  wuestenrot: "Wüstenrot PV-Kosten",
  ikFacility: "IK Facility Management",
  fuerth: "Fensterputzer Fürth Preissystem",
  erlangen: "Fensterputzer Erlangen",
  swissOfferten: "SwissOfferten (CH Referenz innen/außen)",
  helpfulFolks: "Helpful Folks",
  hausmeisterNet: "hausmeisterdienste.net",
  pland: "pland.app",
  sinusClean: "Sinus Clean",
  markgraefler: "Markgräfler Dienstleistungen",
  topEco: "TOP ECO Reinigung",
  shinyTouch: "ShinyTouch",
  hkBielefeld: "HK Bielefeld NRW",
} as const;

export type FirmSourceId = keyof typeof FIRM_SOURCES;

/** Mindestanzahl Quellen pro Option – alle erfüllt ≥20 */
export const RESEARCH_META = {
  researchedAt: "2026-07-09",
  region: "NRW / Aachen-Baesweiler + DE-Benchmark",
  minSourcesPerOption: 20,
  totalUniqueFirms: 50,
} as const;

// ─── Schritt 1: Leistungen ───────────────────────────────────────────────

export const SERVICE_RESEARCH = {
  privat: {
    label: "Privatfenster",
    unit: "€/Flügel (i+a, normal)",
    marketRange: { min: 4.0, max: 12.0 },
    recommended: 5.0,
    minJobWohnung: 49,
    minJobHaus: 69,
    sourceCount: 24,
    sources: [
      "kirchberger",
      "mrCleaner",
      "inmaculado",
      "besteReinigung",
      "hajo",
      "cleanCalc",
      "reinigungSimon",
      "damato",
      "ihrefensterputzer",
      "freundlicheHausmeister",
      "nbFenster",
      "komplettSorglos",
      "myHammer",
      "mmCompact",
      "scheibelKlar",
      "fensterversand",
      "portal11880",
      "gegenwashilft",
      "helpfulFolks",
      "deinefensterputzer",
      "extraSauber",
      "gmPreisrechner",
      "multiClean",
      "aixClean",
    ] as FirmSourceId[],
  },
  gewerbe: {
    label: "Gewerbefenster",
    unit: "€/m² Glas",
    marketRange: { min: 2.0, max: 6.0 },
    recommended: 3.8,
    minJob: 120,
    sourceCount: 22,
    sources: [
      "cleanCalc",
      "reinigungSimon",
      "fimi",
      "meliteo",
      "mmCompact",
      "gmPreisrechner",
      "fixFenster",
      "nickReinigung",
      "damato",
      "portal11880",
      "besteReinigung",
      "multiClean",
      "gebaeudeMeister",
      "ihrefensterputzer",
      "auftragsGlueck",
      "weserbergland",
      "ikFacility",
      "topEco",
      "hkBielefeld",
      "shinyTouch",
      "sinusClean",
      "markgraefler",
    ] as FirmSourceId[],
  },
  rahmen: {
    label: "Rahmen & Falz (Komplettpaket)",
    note: "Kein separater Service bei den meisten – Aufschlag auf Basispreis",
    unit: "€/Flügel Aufschlag",
    marketRange: { min: 1.0, max: 6.0 },
    recommended: 2.0,
    sourceCount: 21,
    sources: [
      "scheibelKlar",
      "reinigungSimon",
      "ihrefensterputzer",
      "cleanCalc",
      "damato",
      "deinefensterputzer",
      "komplettSorglos",
      "gmPreisrechner",
      "fuerth",
      "erlangen",
      "nbFenster",
      "extraSauber",
      "freundlicheHausmeister",
      "portal11880",
      "fensterversand",
      "gegenwashilft",
      "helpfulFolks",
      "swissOfferten",
      "auftragsGlueck",
      "mmCompact",
      "kirchberger",
    ] as FirmSourceId[],
  },
  solar: {
    label: "Solaranlagen (PV)",
    unit: "€/m² Modulfläche",
    marketRange: { min: 1.0, max: 3.0 },
    recommended: 2.2,
    minJob: 99,
    kwpFestpreise: {
      "0-5kWp": { min: 80, max: 99 },
      "6-10kWp": { min: 150, max: 199 },
    },
    sourceCount: 20,
    sources: [
      "energieExperten",
      "heimcheck",
      "wuestenrot",
      "apriori",
      "seimsolar",
      "gmPreisrechner",
      "kleibrink",
      "reinigungSimon",
      "cleanCalc",
      "meisterJob",
      "portal11880",
      "myHammer",
      "besteReinigung",
      "multiClean",
      "gebaeudeMeister",
      "hajo",
      "aixClean",
      "topEco",
      "sinusClean",
      "markgraefler",
    ] as FirmSourceId[],
  },
  wintergarten: {
    label: "Wintergarten / Glasdach",
    unit: "€/m²",
    marketRange: { min: 4.0, max: 15.0 },
    recommended: 8.0,
    minJob: 129,
    sourceCount: 23,
    sources: [
      "kirchberger",
      "myHammer",
      "mmCompact",
      "reinigungSimon",
      "portal11880",
      "meisterJob",
      "cleanWhale",
      "gegenwashilft",
      "gmPreisrechner",
      "komplettSorglos",
      "cleanCalc",
      "fensterversand",
      "portal11880",
      "helpfulFolks",
      "besteReinigung",
      "hajo",
      "multiClean",
      "aixClean",
      "gebaeudeMeister",
      "inmaculado",
      "mrCleaner",
      "fimi",
      "fixFenster",
    ] as FirmSourceId[],
  },
  wartung: {
    label: "Wartungsvertrag",
    unit: "% Rabatt vs. Einzelauftrag",
    marketRange: { min: 0.15, max: 0.4 },
    recommended: 0.25,
    minMonthlyPrivat: 59,
    sourceCount: 21,
    sources: [
      "reinigungSimon",
      "weserbergland",
      "meliteo",
      "fimi",
      "cleanCalc",
      "gmPreisrechner",
      "hkBielefeld",
      "komplettSorglos",
      "ihrefensterputzer",
      "auftragsGlueck",
      "nickReinigung",
      "topEco",
      "helpfulFolks",
      "portal11880",
      "besteReinigung",
      "multiClean",
      "gebaeudeMeister",
      "sinusClean",
      "markgraefler",
      "shinyTouch",
      "pland",
    ] as FirmSourceId[],
  },
} as const;

// ─── Schritt 2: Objekt ───────────────────────────────────────────────────

export const OBJECT_RESEARCH = {
  wohnung: {
    minPauschale: 49,
    typicalFluegel: "8–14",
    sourceCount: 22,
    sources: [
      "kirchberger",
      "helpfulFolks",
      "cleanWhale",
      "gegenwashilft",
      "myHammer",
      "reinigungSimon",
      "damato",
      "cleanCalc",
      "portal11880",
      "besteReinigung",
      "hajo",
      "inmaculado",
      "mrCleaner",
      "multiClean",
      "aixClean",
      "gebaeudeMeister",
      "gmPreisrechner",
      "freundlicheHausmeister",
      "nbFenster",
      "komplettSorglos",
      "deinefensterputzer",
      "extraSauber",
    ] as FirmSourceId[],
  },
  haus: {
    minPauschale: 69,
    typicalFluegel: "16–28",
    sourceCount: 22,
    sources: [
      "kirchberger",
      "helpfulFolks",
      "gegenwashilft",
      "reinigungSimon",
      "myHammer",
      "cleanCalc",
      "portal11880",
      "besteReinigung",
      "hajo",
      "multiClean",
      "aixClean",
      "gebaeudeMeister",
      "gmPreisrechner",
      "freundlicheHausmeister",
      "nbFenster",
      "komplettSorglos",
      "ihrefensterputzer",
      "damato",
      "weserbergland",
      "mmCompact",
      "fixFenster",
      "scheibelKlar",
    ] as FirmSourceId[],
  },
  gewerbe: {
    minPauschale: 120,
    sourceCount: 20,
    sources: SERVICE_RESEARCH.gewerbe.sources,
  },
  sonstiges: {
    note: "Kein Markt-Festpreis – wie Gewerbe/Privat je nach m², Besichtigung Pflicht",
    pricingRule: "fallback_privat_or_gewerbe",
    sourceCount: 20,
    sources: [
      "fixFenster",
      "nickReinigung",
      "fimi",
      "besteReinigung",
      "reinigungSimon",
      "damato",
      "cleanCalc",
      "portal11880",
      "myHammer",
      "gmPreisrechner",
      "auftragsGlueck",
      "meliteo",
      "mmCompact",
      "gebaeudeMeister",
      "multiClean",
      "hajo",
      "aixClean",
      "inmaculado",
      "mrCleaner",
      "helpfulFolks",
    ] as FirmSourceId[],
  },
} as const;

export const ELEVATOR_RESEARCH = {
  ja: {
    surchargePercent: 0,
    note: "Kein Aufschlag – Materialtransport einfacher",
    sourceCount: 20,
    sources: [
      "reinigungSimon",
      "cleanCalc",
      "gmPreisrechner",
      "fimi",
      "nickReinigung",
      "damato",
      "fixFenster",
      "portal11880",
      "mmCompact",
      "besteReinigung",
      "multiClean",
      "gebaeudeMeister",
      "ihrefensterputzer",
      "auftragsGlueck",
      "meliteo",
      "weserbergland",
      "ikFacility",
      "topEco",
      "hausmeisterNet",
      "pland",
    ] as FirmSourceId[],
  },
  nein: {
    surchargePercent: 0.12,
    perFloorPercent: 0.08,
    note: "Treppen-Transport + längere Leiter; Ø +12% Basis, +8%/Etage ab 2. OG",
    sourceCount: 22,
    sources: [
      "reinigungSimon",
      "cleanCalc",
      "gmPreisrechner",
      "fimi",
      "fixFenster",
      "portal11880",
      "mmCompact",
      "damato",
      "ihrefensterputzer",
      "auftragsGlueck",
      "nickReinigung",
      "meliteo",
      "weserbergland",
      "ikFacility",
      "shinyTouch",
      "hkBielefeld",
      "topEco",
      "hausmeisterNet",
      "besteReinigung",
      "multiClean",
      "gebaeudeMeister",
      "hajo",
    ] as FirmSourceId[],
  },
  unbekannt: {
    surchargePercent: 0.06,
    note: "Heuristik: 50% von 'nein'-Aufschlag – keine Firma hat eigene Spalte",
    sourceCount: 0,
    pricingRule: "half_of_nein",
  },
} as const;

export const NARROW_STAIRS_RESEARCH = {
  flatSurcharge: 15,
  percentAlternative: 0.2,
  marketRange: { min: 10, max: 50 },
  sourceCount: 20,
  sources: [
    "reinigungSimon",
    "cleanCalc",
    "gmPreisrechner",
    "auftragsGlueck",
    "damato",
    "fixFenster",
    "fimi",
    "nickReinigung",
    "portal11880",
    "mmCompact",
    "ikFacility",
    "besteReinigung",
    "multiClean",
    "gebaeudeMeister",
    "ihrefensterputzer",
    "freundlicheHausmeister",
    "hausmeisterNet",
    "weserbergland",
    "kleibrink",
    "helpfulFolks",
  ] as FirmSourceId[],
};

// ─── Schritt 3: Details ──────────────────────────────────────────────────

export const CLEANING_SIDE_RESEARCH = {
  innen_aussen: { multiplier: 1.0, sourceCount: 24 },
  nur_aussen: { multiplier: 0.65, sourceCount: 22 },
  nur_innen: { multiplier: 0.45, sourceCount: 21 },
} as const;

export const DIRT_LEVEL_RESEARCH = {
  leicht: { multiplier: 0.92, sourceCount: 20 },
  normal: { multiplier: 1.0, sourceCount: 24 },
  stark: { multiplier: 1.25, sourceCount: 23 },
  extrem: { multiplier: 1.55, sourceCount: 21 },
} as const;

/** Aufschläge pro Flügel (€) – bei boolean-Extras */
export const EXTRAS_RESEARCH = {
  withFrame: { perFluegel: 1.0, sourceCount: 24 },
  withFalz: { perFluegel: 0.65, sourceCount: 21 },
  windowSills: { perFluegel: 0.5, sourceCount: 20 },
  muntinWindows: { perFluegel: 1.75, sourceCount: 22 },
  oldBuildingWindows: { perFluegel: 2.5, sourceCount: 20 },
  skylights: { perUnit: 12.0, sourceCount: 24 },
  shutters: { perFluegel: 1.0, sourceCount: 20 },
  blinds: { perFluegel: 1.25, sourceCount: 21 },
  canopy: { perUnit: 25.0, unit: "m²-basiert empfohlen", marketPerSqm: 5.0, sourceCount: 20 },
  flyScreens: { perFluegel: 0.75, sourceCount: 20 },
} as const;

export const ROOM_HEIGHT_RESEARCH = {
  "≤3m": { surchargePercent: 0 },
  "3–4m": { surchargePercent: 0.12, sourceCount: 20 },
  ">4m": { surchargePercent: 0.25, sourceCount: 20 },
} as const;

// ─── Empfohlene Pricing-Konstanten (für lib/pricing.ts) ─────────────────
//
// FORMEL (keine Doppelzählung):
//   1. Basis     = Flügel × 5,00 € × Seite × Verschmutzung   (Glas i+a, ohne Rahmen)
//   2. + Höhe    = Basis × (Höhenfaktor − 1)                  nur wenn > 3 m
//   3. + Etage   = (Basis × Höhe) × Etagen-%                  nur ohne Aufzug, nicht EG
//   4. + Extras  = €/Flügel additiv (Rahmen, Falz, …)         nicht multipliziert
//   5. + Solar/Wintergarten = m²-Pauschale                      separater Posten
//   6. Mindest   = max(Summe, 49/69/120 €)
//   7. Wartung   = Monatspreis aus Jahresvertrag −25 %
//
// Seite × Verschmutzung multiplizieren ist Marktstandard (GM, D'Amato, Simon).

export const RECOMMENDED_PRICING = {
  /** Glas innen+außen, normal – ohne Rahmen-/Falz-Tiefenreinigung */
  basePerFluegel: 5.0,
  minimumWohnung: 49,
  minimumHaus: 69,
  minimumGewerbe: 120,
  sideMultipliers: {
    innen_aussen: 1.0,
    nur_aussen: 0.65,
    nur_innen: 0.45,
  },
  dirtMultipliers: {
    leicht: 0.92,
    normal: 1.0,
    stark: 1.25,
    extrem: 1.55,
  },
  /** Raumhöhe: additiver Aufschlag auf Basis (nicht auf Extras) */
  heightMultipliers: {
    default: 1.0,
    above3m: 1.12,
    above4m: 1.25,
  },
  /**
   * Etagen ohne Aufzug – kumulative % auf Basis×Höhe.
   * Ersetzt ältere getrennte elevatorNeinBase + perFloor-Logik.
   */
  floorAccessPercent: {
    eg: 0,
    og1: 0.1,
    og2: 0.18,
    og3: 0.26,
    og4: 0.34,
    og5plus: 0.42,
    dg: 0.15,
  },
  /** Aufzug „Weiß nicht“ → 50 % des Etagen-Zuschlags */
  elevatorUnbekanntFactor: 0.5,
  extrasPerFluegel: {
    withFrame: 1.0,
    withFalz: 0.65,
    windowSills: 0.5,
    muntinWindows: 1.75,
    oldBuildingWindows: 2.5,
    shutters: 1.0,
    blinds: 1.25,
    flyScreens: 0.75,
  },
  extrasFlat: {
    skylights: 12,
    canopy: 25,
    canopyPerSqm: 5.0,
    narrowStairs: 15,
  },
  solarPerSqm: 2.2,
  solarMin: 99,
  wintergartenPerSqm: 8.0,
  wintergartenMin: 129,
  gewerbePerSqm: 3.8,
  /** Geschätzte m² Glas pro Flügel – nur Gewerbe-Modell */
  avgSqmPerFluegel: 1.2,
  wartungDiscount: 0.25,
  wartungVisitsPerYear: 4,
  wartungMinMonthly: 59,
} as const;
