/**
 * Seed configuration — market-mid calibration (2026).
 *
 * Time bases cross-checked against:
 * - RAL GGGR Merkblatt Leistungszahlen Unterhaltsreinigung (Juli 2020)
 * - BIV Leistungskennziffern (praxis ranges cited in trade press)
 * - DE market mid visit prices / durations 2026 (Wischkahl, Andonov, Kleibrink, CleanCalc)
 *
 * Rates remain CALIBRATION_REQUIRED until object Probereinigung — not a licensed ISSA table.
 */

import type {
  MeasurementType,
  OverheadModel,
  RateStatus,
  RateType,
  RoundingMode,
  SourceType,
} from "./types";
import { eurosToCents, type EuroCents } from "./money";

export interface TaskRateSeed {
  id: string;
  category: string;
  nameDE: string;
  nameTR: string;
  measurementType: MeasurementType;
  unit: string;
  baseRate: number;
  rateType: RateType;
  tool: string;
  active: boolean;
  version: string;
  sourceType: SourceType;
  status: RateStatus;
  sourceReference: string;
  includesTaskIds: string[];
  excludesTaskIds: string[];
  notes: string;
}

export interface CleaningEngineConfig {
  configVersionId: string;
  effectiveFrom: string;
  lg1GrossHourlyEuros: number;
  /** Burdened productive hour cost (wage + LN + Ausfall share) — CALIBRATION */
  productiveHourCostCents: EuroCents;
  productivePaidTimeRatio: number;
  targetGrossMargin: number;
  minimumGrossMargin: number;
  minimumBillablePersonHours: number;
  minimumJobNetCents: EuroCents;
  vatRateBps: number;
  vatEffectiveFrom: string;
  overheadModel: OverheadModel;
  overheadPercentOfDirect: number;
  overheadPerHourCents: EuroCents;
  teamEfficiency: Record<1 | 2 | 3 | 4, number>;
  maxTeamSize: number;
  targetOnsiteHours: number;
  rounding: RoundingMode;
  conditionFactors: Record<string, number>;
  usageFactors: Record<string, number>;
  /** Workload efficiency for recurring — NOT commercial discount */
  frequencyWorkloadFactors: Record<string, number>;
  /** Commercial discount on selling price after cost/margin */
  frequencyCommercialDiscounts: Record<string, number>;
  tasks: TaskRateSeed[];
}

/** LG1 Innen-/Unterhaltsreinigung floor 2026-01-01 — verify BMAS before go-live. */
export const LG1_2026_GROSS_HOURLY = 15;

/**
 * Market-mid sell ≈ 38–39 €/h netto:
 * productive 27 € × (1+12% OH) / (1−22% margin) ≈ 38.77 €/h.
 * Aligns with Facento/CleanCalc Unterhalt mid band (≈25–35 € + quality mid).
 */
export const DEFAULT_CLEANING_CONFIG: CleaningEngineConfig = {
  configVersionId: "cleaning-config-2026-market-v3",
  effectiveFrom: "2026-01-01",
  lg1GrossHourlyEuros: LG1_2026_GROSS_HOURLY,
  productiveHourCostCents: eurosToCents(27),
  productivePaidTimeRatio: 0.75,
  targetGrossMargin: 0.22,
  minimumGrossMargin: 0.15,
  /** Small jobs: Anfahrt/Rüst still billed — 1.5 Pers.-Std. floor */
  minimumBillablePersonHours: 1.5,
  minimumJobNetCents: eurosToCents(65),
  vatRateBps: 1900,
  vatEffectiveFrom: "2026-01-01",
  overheadModel: "PERCENTAGE_OF_DIRECT_COST",
  overheadPercentOfDirect: 0.12,
  overheadPerHourCents: eurosToCents(8),
  teamEfficiency: { 1: 1, 2: 1.85, 3: 2.55, 4: 3.2 },
  maxTeamSize: 4,
  /** Typical visit window mid — Wischkahl 100–200 m² ≈ 1.5–3.5 Std. */
  targetOnsiteHours: 2.5,
  rounding: "0.50",
  conditionFactors: {
    MAINTAINED: 0.9,
    NORMAL: 1,
    NEGLECTED: 1.25,
    INITIAL_INTENSIVE: 1.6,
  },
  usageFactors: {
    LOW: 0.9,
    NORMAL: 1,
    HIGH: 1.2,
  },
  frequencyWorkloadFactors: {
    ONE_TIME: 1.15,
    "1_PER_WEEK": 1,
    "2_PER_WEEK": 0.95,
    "3_PER_WEEK": 0.9,
    "5_PER_WEEK": 0.85,
    CUSTOM: 1,
  },
  frequencyCommercialDiscounts: {
    ONE_TIME: 0,
    "1_PER_WEEK": 0,
    "2_PER_WEEK": 0.02,
    "3_PER_WEEK": 0.04,
    "5_PER_WEEK": 0.06,
    CUSTOM: 0,
  },
  tasks: [
    // —— Room types (primary time from subAreas; RAL mid slowed to commercial full-LV) ——
    {
      id: "room_office",
      category: "room",
      nameDE: "Bürofläche (Raumleistung)",
      nameTR: "Ofis alanı",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 105,
      rateType: "UNITS_PER_HOUR",
      tool: "mixed",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_BUERO_160_230_COMMERCIAL_FULL_LV",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Below RAL optimistic mid; matches ~50–70 m²/h object with fixtures",
    },
    {
      id: "room_meeting",
      category: "room",
      nameDE: "Besprechungsfläche",
      nameTR: "Toplantı alanı",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 125,
      rateType: "UNITS_PER_HOUR",
      tool: "mixed",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_MEETING_150_280",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "room_kitchen",
      category: "room",
      nameDE: "Teeküchenfläche",
      nameTR: "Mutfak alanı",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 80,
      rateType: "UNITS_PER_HOUR",
      tool: "mixed",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_TEEKUECHE_80_150",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "room_sanitary",
      category: "room",
      nameDE: "Sanitärfläche",
      nameTR: "Sanitasyon alanı",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 55,
      rateType: "UNITS_PER_HOUR",
      tool: "mixed",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_SANITAER_60_90",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Includes typical sanitary floor; fixtures refine density",
    },
    {
      id: "room_corridors",
      category: "room",
      nameDE: "Flure / Verkehr",
      nameTR: "Koridor",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 200,
      rateType: "UNITS_PER_HOUR",
      tool: "mop",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_FLURE_MANUELL_250_350",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Manual corridor mid-low of RAL span",
    },
    {
      id: "room_reception",
      category: "room",
      nameDE: "Empfang / Eingang",
      nameTR: "Resepsiyon",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 180,
      rateType: "UNITS_PER_HOUR",
      tool: "mixed",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_EINGANG_250_600",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Conservative vs open foyer highs",
    },
    {
      id: "room_other",
      category: "room",
      nameDE: "Nebenräume",
      nameTR: "Diğer odalar",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 200,
      rateType: "UNITS_PER_HOUR",
      tool: "mop",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_NEBEN_250_350",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    // —— Floor modifiers (rooms carry primary floor time; avoid double count) ——
    {
      id: "carpet_surcharge",
      category: "floor",
      nameDE: "Teppich-Zuschlag",
      nameTR: "Halı ek süre",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 550,
      rateType: "UNITS_PER_HOUR",
      tool: "vacuum",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "TEXTILE_VS_HARD_PRACTICE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "~+11% vs hard when carpet share high (550 m²/h surcharge minutes)",
    },
    {
      id: "carpet_vacuum",
      category: "floor",
      nameDE: "Teppich saugen (Fallback)",
      nameTR: "Halı süpürme (yedek)",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 145,
      rateType: "UNITS_PER_HOUR",
      tool: "vacuum",
      active: false,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "DEPRECATED",
      sourceReference: "REPLACED_BY_ROOM_PLUS_CARPET_SURCHARGE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Deprecated — rooms + carpet_surcharge",
    },
    {
      id: "hard_floor_damp_mop",
      category: "floor",
      nameDE: "Hartboden feucht wischen (Fallback)",
      nameTR: "Sert zemin (yedek)",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 160,
      rateType: "UNITS_PER_HOUR",
      tool: "mop",
      active: false,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "DEPRECATED",
      sourceReference: "REPLACED_BY_ROOM_RATES",
      includesTaskIds: [],
      excludesTaskIds: ["wet_floor_clean"],
      notes: "Deprecated — included in room_*",
    },
    {
      id: "wet_floor_clean",
      category: "floor",
      nameDE: "Nassbereich Boden (Zusatz)",
      nameTR: "Islak zemin ek",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 65,
      rateType: "UNITS_PER_HOUR",
      tool: "wet",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_SANITAER_60_90",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Only m² above sanitary room area to avoid double count with room_sanitary",
    },
    {
      id: "other_floor_clean",
      category: "floor",
      nameDE: "Sonstige Bodenflächen (Fallback)",
      nameTR: "Diğer zemin (yedek)",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 160,
      rateType: "UNITS_PER_HOUR",
      tool: "mop",
      active: false,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "DEPRECATED",
      sourceReference: "REPLACED_BY_ROOM_OTHER",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Deprecated",
    },
    // —— Office surfaces (refinement on top of room package) ——
    {
      id: "desk_surfaces",
      category: "office",
      nameDE: "Schreibtischflächen",
      nameTR: "Masa yüzeyleri",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.35,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_DESK_20S_ROOM_ADJUSTED",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Light refinement — room_office already includes typical surfaces",
    },
    {
      id: "office_bin_empty",
      category: "office",
      nameDE: "Papierkorb leeren",
      nameTR: "Çöp kutusu boşaltma",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.4,
      rateType: "MINUTES_PER_UNIT",
      tool: "bin",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_BIN_45S_ROOM_ADJUSTED",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "RAL 45s; reduced vs pure floor model because rooms include waste share",
    },
    {
      id: "meeting_chair_wipe",
      category: "office",
      nameDE: "Meetingstuhl abwischen",
      nameTR: "Toplantı sandalyesi silme",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.35,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_CHAIR_WIPE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Light wipe armrests/back — not deep upholstery",
    },
    {
      id: "cabinet_exterior",
      category: "office",
      nameDE: "Schrankfronten (Büro)",
      nameTR: "Dolap dış yüzeyleri",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.4,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_LV_SCHRAENKE_PROXY",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Quantity = workstations when option enabled",
    },
    {
      id: "shelving_wipe",
      category: "office",
      nameDE: "Regale abwischen",
      nameTR: "Raf silme",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.25,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_SHELF",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Quantity = workstations when option enabled",
    },
    {
      id: "window_sill_wipe",
      category: "office",
      nameDE: "Fensterbänke",
      nameTR: "Pencere pervazı",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.15,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_SILLS_5S",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "RAL ~5s/room; scaled per workstation proxy",
    },
    {
      id: "phone_monitor_exterior",
      category: "office",
      nameDE: "Telefon/Monitor außen",
      nameTR: "Telefon/monitör dışı",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.2,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_PHONE_5S",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "RAL Telefon 5s; practice buffer to 12s",
    },
    {
      id: "whiteboard_wipe",
      category: "office",
      nameDE: "Whiteboard reinigen",
      nameTR: "Yazı tahtası",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 1.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_WHITEBOARD",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Quantity = meetingRooms (min 1) when enabled",
    },
    // —— Sanitary fixtures (BIV WC-Anlage ~1:50 for full set; split per fixture) ——
    {
      id: "toilet_fixture",
      category: "sanitary",
      nameDE: "WC reinigen/desinfizieren",
      nameTR: "WC temizleme/dezenfeksiyon",
      measurementType: "FIXTURE",
      unit: "Stk",
      baseRate: 2,
      rateType: "MINUTES_PER_UNIT",
      tool: "sanitary",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "BIV_WC_SET_SPLIT+ROOM_SANITARY",
      includesTaskIds: [],
      excludesTaskIds: ["wet_floor_clean", "room_sanitary"],
      notes: "Density refine — room_sanitary carries floor/base",
    },
    {
      id: "urinal_fixture",
      category: "sanitary",
      nameDE: "Urinal reinigen",
      nameTR: "Pisuvar temizleme",
      measurementType: "FIXTURE",
      unit: "Stk",
      baseRate: 1.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "sanitary",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "BIV_URINAL_SHARE",
      includesTaskIds: [],
      excludesTaskIds: ["wet_floor_clean", "room_sanitary"],
      notes: "Fixture density refine",
    },
    {
      id: "washbasin_fixture",
      category: "sanitary",
      nameDE: "Waschbecken reinigen",
      nameTR: "Lavabo temizleme",
      measurementType: "FIXTURE",
      unit: "Stk",
      baseRate: 1.2,
      rateType: "MINUTES_PER_UNIT",
      tool: "sanitary",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "BIV_WASHBASIN_SHARE",
      includesTaskIds: [],
      excludesTaskIds: ["wet_floor_clean", "room_sanitary"],
      notes: "Incl. Armaturen lightly",
    },
    {
      id: "mirror_clean",
      category: "sanitary",
      nameDE: "Spiegel reinigen",
      nameTR: "Ayna temizleme",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.8,
      rateType: "MINUTES_PER_UNIT",
      tool: "glass",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_MIRROR",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Spot-free wipe",
    },
    {
      id: "sanitary_bin_empty",
      category: "sanitary",
      nameDE: "Sanitärabfall leeren",
      nameTR: "Hijyen çöpü",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "bin",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "BIV_SANITARY_BIN_25S",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "BIV Abfallbehälter ~25s + bag",
    },
    {
      id: "shower_fixture",
      category: "sanitary",
      nameDE: "Dusche reinigen",
      nameTR: "Duş temizleme",
      measurementType: "FIXTURE",
      unit: "Stk",
      baseRate: 4,
      rateType: "MINUTES_PER_UNIT",
      tool: "sanitary",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_SANITAER_SHOWER_SHARE",
      includesTaskIds: [],
      excludesTaskIds: ["wet_floor_clean"],
      notes: "Cabin walls + tray; floor m² separate",
    },
    {
      id: "cubicle_wipe",
      category: "sanitary",
      nameDE: "Trennwände/Kabinen",
      nameTR: "Kabin bölmeleri",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 1.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "sanitary",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "BIV_TILE_SPLASH_PROXY",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Splash-zone wipe per cubicle",
    },
    // —— Kitchen ——
    {
      id: "kitchen_base",
      category: "kitchen",
      nameDE: "Teeküche Basis",
      nameTR: "Çay mutfağı baz",
      measurementType: "ROOM",
      unit: "Küche",
      baseRate: 6,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v3-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_TEEKUECHE_PLUS_COUNTS",
      includesTaskIds: ["kitchen_bin_empty"],
      excludesTaskIds: ["room_kitchen"],
      notes: "Count refine on top of room_kitchen m²",
    },
    {
      id: "kitchen_bin_empty",
      category: "kitchen",
      nameDE: "Küchenabfall leeren",
      nameTR: "Mutfak çöpü boşaltma",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "bin",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_KITCHEN_BIN",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Skipped when kitchen_base includesTaskIds",
    },
    {
      id: "kitchen_table",
      category: "kitchen",
      nameDE: "Küchentisch",
      nameTR: "Mutfak masası",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 2,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_KITCHEN_TABLE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "kitchen_chair",
      category: "kitchen",
      nameDE: "Küchenstuhl",
      nameTR: "Mutfak sandalyesi",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 0.35,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_KITCHEN_CHAIR",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "kitchen_sink",
      category: "kitchen",
      nameDE: "Küchenspüle",
      nameTR: "Mutfak eviyesi",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 2,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_SINK",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "kitchen_counter",
      category: "kitchen",
      nameDE: "Arbeitsplatte",
      nameTR: "Tezgâh",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 1.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_COUNTER",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "appliance_exterior",
      category: "kitchen",
      nameDE: "Geräte außen",
      nameTR: "Cihaz dışı",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 1.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_APPLIANCE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "",
    },
    {
      id: "microwave_inside",
      category: "kitchen",
      nameDE: "Mikrowelle innen",
      nameTR: "Mikrodalga içi",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 5,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_MICROWAVE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Optional — never silent in routine",
    },
    {
      id: "refrigerator_inside",
      category: "kitchen",
      nameDE: "Kühlschrank innen",
      nameTR: "Buzdolabı içi",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 8,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_FRIDGE",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Optional intensive",
    },
    {
      id: "dishwasher_exterior",
      category: "kitchen",
      nameDE: "Spülmaschine außen/Tür",
      nameTR: "Bulaşık makinesi dışı",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 3,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_DISHWASHER",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Quantity = kitchens when option enabled",
    },
    {
      id: "kitchen_cabinet_fronts",
      category: "kitchen",
      nameDE: "Küchenfronten",
      nameTR: "Mutfak kapakları",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 4,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_KITCHEN_FRONTS",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Quantity = kitchens when option enabled",
    },
    {
      id: "dishes_wash",
      category: "kitchen",
      nameDE: "Geschirr spülen",
      nameTR: "Bulaşık",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 10,
      rateType: "MINUTES_PER_UNIT",
      tool: "sink",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_DISHES",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Optional; often excluded from Unterhalt LV",
    },
    // —— Additional ——
    {
      id: "stair_flight",
      category: "additional",
      nameDE: "Treppenlauf",
      nameTR: "Merdiven sahanlığı",
      measurementType: "COUNT",
      unit: "Etage",
      baseRate: 12,
      rateType: "MINUTES_PER_UNIT",
      tool: "mop",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_TREPPEN_130_200",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "~15–20 m² flight+landing @ ~165 m²/h → ~7–8 min; buffer 12",
    },
    {
      id: "elevator_cabin",
      category: "additional",
      nameDE: "Aufzugskabine",
      nameTR: "Asansör kabini",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 5,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_AUFZUG_90_150",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Cabin ~4–6 m² @ mid ~120 m²/h + wipe",
    },
    {
      id: "glass_entrance_door",
      category: "additional",
      nameDE: "Glastür Eingang",
      nameTR: "Cam giriş kapısı",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 2.5,
      rateType: "MINUTES_PER_UNIT",
      tool: "glass",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GLAS_TUER_SPOT_CLEAN",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Unterhalt Griffspuren/glass spot — not full Glasreinigung",
    },
    {
      id: "reception_detail",
      category: "additional",
      nameDE: "Empfang Detail",
      nameTR: "Resepsiyon detay",
      measurementType: "COUNT",
      unit: "Stk",
      baseRate: 8,
      rateType: "MINUTES_PER_UNIT",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_RECEPTION",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Quantity 1 when option enabled",
    },
    {
      id: "high_touch_areas",
      category: "additional",
      nameDE: "Griffzonen/High-Touch",
      nameTR: "Sık dokunulan yerler",
      measurementType: "AREA_M2",
      unit: "m²",
      baseRate: 1200,
      rateType: "UNITS_PER_HOUR",
      tool: "cloth",
      active: true,
      version: "v2-market",
      sourceType: "ADMIN_ESTIMATE",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "PRACTICE_HIGH_TOUCH",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "≈3 min / 60 m² when enabled (1200 m²/h)",
    },
    // —— Visit fixed ——
    {
      id: "setup_travel",
      category: "overhead",
      nameDE: "Rüst-/Wegezeit je Einsatz",
      nameTR: "Hazırlık/yol süresi",
      measurementType: "COUNT",
      unit: "Einsatz",
      baseRate: 22,
      rateType: "MINUTES_PER_UNIT",
      tool: "setup",
      active: true,
      version: "v2-market",
      sourceType: "PUBLIC_BENCHMARK",
      status: "CALIBRATION_REQUIRED",
      sourceReference: "RAL_GGGR_2020_RUEST_WEGE+PRACTICE_15_25",
      includesTaskIds: [],
      excludesTaskIds: [],
      notes: "Fixed per visit; RAL stresses Rüst/Wege must be in Leistungszahl",
    },
  ],
};
